algo = input('Digite algo: ')
print('É Alfanumerico? {}'.format(algo.isalnum()), type(algo))
print('É somente minusculo ? {}'.format(algo.islower()), type(algo))
print('É numerico? {}'.format(algo.isnumeric()), type(algo))
print('É Alfa ? {}'.format(algo.isalpha()), type(algo))
print('É decimal ? {}'.format(algo.isdecimal()), type(algo))
print('É todo maiusculo ? {}'.format(algo.isupper()), type(algo))