number = int(input('Digite um numero para saber a sua respectiva tabuada: '))
print('='*15)

print('Tabuada da Soma')

print('{} + {} = {}'.format(1, number, (number+1)))
print('{} + {} = {}'.format(2, number, (number+2)))
print('{} + {} = {}'.format(3, number, (number+3)))
print('{} + {} = {}'.format(4, number, (number+4)))
print('{} + {} = {}'.format(5, number, (number+5)))
print('{} + {} = {}'.format(6, number, (number+6)))
print('{} + {} = {}'.format(7, number, (number+7)))
print('{} + {} = {}'.format(8, number, (number+8)))
print('{} + {} = {}'.format(9, number, (number+9)))
print('='*15)

print('Tabuada da Subtração')

print('='*15)
print('{} - {} = {}'.format(1, number, (number-1)))
print('{} - {} = {}'.format(2, number, (number-2)))
print('{} - {} = {}'.format(3, number, (number-3)))
print('{} - {} = {}'.format(4, number, (number-4)))
print('{} - {} = {}'.format(5, number, (number-5)))
print('{} - {} = {}'.format(6, number, (number-6)))
print('{} - {} = {}'.format(7, number, (number-7)))
print('{} - {} = {}'.format(8, number, (number-8)))
print('{} - {} = {}'.format(9, number, (number-9)))
print('='*15)

print('tabuada da Multiplicação')

print('='*15)
print('{} x {} = {}'.format(1, number, (number*1)))
print('{} x {} = {}'.format(2, number, (number*2)))
print('{} x {} = {}'.format(3, number, (number*3)))
print('{} x {} = {}'.format(4, number, (number*4)))
print('{} x {} = {}'.format(5, number, (number*5)))
print('{} x {} = {}'.format(6, number, (number*6)))
print('{} x {} = {}'.format(7, number, (number*7)))
print('{} x {} = {}'.format(8, number, (number*8)))
print('{} x {} = {}'.format(9, number, (number*9)))
print('='*15)

print('Tabuada da Divisão')

print('='*15)
print('{} / {} = {:.0f}'.format(1, number, (number/1)))
print('{} / {} = {:.0f}'.format(2, number, (number/2)))
print('{} / {} = {:.0f}'.format(3, number, (number/3)))
print('{} / {} = {:.0f}'.format(4, number, (number/4)))
print('{} / {} = {:.0f}'.format(5, number, (number/5)))
print('{} / {} = {:.0f}'.format(6, number, (number/6)))
print('{} / {} = {:.0f}'.format(7, number, (number/7)))
print('{} / {} = {:.0f}'.format(8, number, (number/8)))
print('{} / {} = {:.0f}'.format(9, number, (number/9)))
print('='*15)


